keywords:
  - 응급
  - 구급
  - 119
  - 구조
  - 안전
  - 화재
  - 불
  - 연기
  - 대피
  - 위험
  - 사고
  - 교통사고
  - 출혈
  - 피
  - 통증
  - 아프
  - 숨
  - 호흡
  - 의식
  - 알레르기
  - 임신
  - 경련
  - 발작
  - 화상
  - 골절
  - 병원
  - 구급차
  - 의사
  - 약
  - 엘리베이터
  - 계단
  - 추락
  - 충돌
  - 붕괴
  - 감전
  - 홍수
  - 침수
  - 사망
  - 가슴
  - 머리
  - 복통
  - 구토
  - 중독
  - 심폐소생
  - 심정지
  - 지진
  - 폭발

archive_categories:
  - EARTHQUAKE
  - TSUNAMIEARTHQUAKE
  - FLOODING
  - DELUGEFLOOD
  - FIRE
  - FORESTFIRE
  - EXPLOSION
  - COLLAPSEBUILDING
  - ELECTRICGASACCIDENT
  - TRAFFICACCIDENT
  - RAILWAYSUBWAYTAXIACCIDENT
  - ELEVATORSAFETYACCIDENT
  - FIRSTAID
  - CHEMICALACCIDENT
  - NUCLEARACCIDENT
  - MOUNTAINSAFETYACCIDENT
